# -*- coding: utf-8 -*-
"""Final Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tlIUmFhnrUKuOZKVApwe0CDvLxwKKTWc
"""

import pandas as pd

# ===== paths (change if needed) =====
AUDUSD_D = "audusd_daily_clean.csv"
AUDUSD_H = "audusd_hourly_clean.csv"
CMDTY_D  = "commodities_daily_clean.csv"
CMDTY_H  = "commodities_hourly_clean.csv"

# ===== load =====
aud_d = pd.read_csv(AUDUSD_D, parse_dates=["Date"], index_col="Date").sort_index()
aud_h = pd.read_csv(AUDUSD_H, parse_dates=["Date"], index_col="Date").sort_index()
cmd_d = pd.read_csv(CMDTY_D,  parse_dates=["Date"], index_col="Date").sort_index()
cmd_h = pd.read_csv(CMDTY_H,  parse_dates=["Date"], index_col="Date").sort_index()

# (optional) sanity checks
assert aud_d.index.is_monotonic_increasing and aud_h.index.is_monotonic_increasing
# print(aud_d.tail(), cmd_d.tail())

# ===== align & combine =====
# DAILY: keep AUDUSD’s timestamps; bring in commodities; forward/back-fill only the commodity side
final_daily = aud_d.join(cmd_d, how="left")
final_daily.loc[:, final_daily.columns.difference(aud_d.columns)] = \
    final_daily.loc[:, final_daily.columns.difference(aud_d.columns)].ffill().bfill()

# HOURLY: same idea for hourly
final_hourly = aud_h.join(cmd_h, how="left")
final_hourly.loc[:, final_hourly.columns.difference(aud_h.columns)] = \
    final_hourly.loc[:, final_hourly.columns.difference(aud_h.columns)].ffill().bfill()

# (optional) drop rows where AUDUSD is missing (shouldn't happen if using clean files)
final_daily = final_daily.dropna(subset=["Close"])
final_hourly = final_hourly.dropna(subset=["Close"])

# ===== save =====
final_daily.to_csv("final_daily.csv", index_label="Date")
final_hourly.to_csv("final_hourly.csv", index_label="Date")

print("final_daily:", final_daily.shape, "-> final_daily.csv")
print("final_hourly:", final_hourly.shape, "-> final_hourly.csv")